apiVersion: v1
kind: Service
metadata:
  name: fastapi-blog-service
  labels:
    app: fastapi-blog
spec:
  selector:
    app: fastapi-blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP